name: CI

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  run-terraform:
    name: "Run terraform"
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        if: false
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ID }}
          aws-region: us-east-2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Run terraform init
        run: terraform init
      - name: Run terraform format
        run: terraform fmt -check
      - name: Run terraform validate
        run: terraform validate
      - name: Run terraform plan
        run: terraform plan
        env:
          TF_VAR_profile: ${{ secrets.AWS_PROFILE }}
      - name: Run terraform apply
        run: terraform apply
        if: false
        env:
          TF_VAR_profile: ${{ secrets.AWS_PROFILE }}
#FIXME:
# Run terraform plan

# Planning failed. Terraform encountered an error while generating this plan.
# ╷
# │ Error: failed to get shared config profile, ***
# │
# │   with provider["registry.terraform.io/hashicorp/aws"],
# │   on main.tf line 10, in provider "aws":
# │   10: provider "aws" {
# │
# ╵
# ::error::Terraform exited with code 1.
